name: Execute SQL

on:
  push:
    branches: [ main ]

jobs:
  execute-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute SQL script
        run: |
          # Instalacja klienta mysql
          sudo apt-get update && sudo apt-get install -y mysql-client
          # Wykonanie skryptu (zakładamy, że plik nazywa się schema.sql)
          mysql -h ${{ secrets.DB_HOST }} -u ${{ secrets.DB_USER }} -p'${{ secrets.DB_PASSWORD }}' ${{ secrets.DB_NAME }} < schema.sql
